### ISSUE TITLE
Schema.org meta data

### ISSUE THREAD

**Issue by pbergonzi** [pbergonzi/legal-card#116]
https://developers.google.com/search/docs/guides/intro-structured-data?authuser=1&visit_id=1-636435487957195214-77669858&hl=es&rd=1

**Comment by pfeldman** [comment]
https://developers.google.com/search/docs/guides/mark-up-content?authuser=1&hl=es#content_types

Aparentemente estos son los unicos tipos a los que se le puede poner schema, por ahora, nosotros no estariamos
