### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by pbergonzi** [pbergonzi/legal-card#29]
The personal data form should validate : 
- full-name should be no more than 70 letters.
- passport (we're doing this only for the us): U.S. Passport numbers must be between six and nine alphanumeric characters (letters and numbers)
- email : should be a valid format email address (any standard regex will do) max length=70

The errors if any should be showed when the user leaves the input or when the user presses the "go to checkout" button, the specific detail of the design of the errors will be provided (red letters under the input and red borders on the same input for now)

**Comment by pfeldman** [comment]
Missing: Show somehow errors occurred
