### ISSUE TITLE
L&F redesign

### ISSUE THREAD

**Issue by pablobergonzi** [pbergonzi/legal-card#57]
Implementar el diseño de Lou en :  
- home screen : por ejemplo se van las fotos de la parte media y entra lugar para video + texto, remover fechas de noticias etc.
- insurance plans : remover galeria y dejar 3 cajas, una para el plan de 45 dias otra para el de un año y la última del plan cosporativo que te manda directo a contact us

**Comment by pfeldman** [comment]
Add Breadcrumb
